swagger: '2.0'
info:
  title: Api podologia
  description: 'Api que almacena y controla los datos de los pacientes'
  version: 1.0.0
host: 'localhost:5000'
basePath: /v1/
consumes:
  - application/json
  - multipart/form-data
produces:
  - application/json

paths:
  /pacientes:
    get:
      tags:
        - Pacientes
      summary: obtiene todos los pacientes
      x-swagger-router-controller: paciente.find
      parameters:
        - name: nombre
          in: query
          description: Nombre del paciente
          required: false
          type: string
        - name: apellido
          in: query
          required: false
          description: Apellido del paciente
          type: string
        - name: dni
          in: query
          description: dni del paciente
          required: false
          type: number
      responses:
        '200':
          description: Devuelve lista de pacientes
    post:
      tags:
        - Pacientes
      summary: Inserta datos del paciente
      x-swagger-router-controller: paciente.insert
      parameters:
        - name: datos
          in: body
          required: true
          schema:
              $ref: '#/definitions/Paciente'
      responses:
        '201':
          description: devuelve las cuentas
  /pacientes/{id}:
    get:
      tags:
        - Pacientes
      summary: Obtiene el paciente por su id
      x-swagger-router-controller: paciente.find
      parameters:
        - name: id
          in: path
          type: string
          description: id del paciente
          required: true
      responses:
        '200':
          description:
            Devuelve paciente
  /pacientes/{id}/historial:
    post:
      tags:
        - Pacientes
      summary: Inserta datos del historial del paciente
      x-swagger-router-controller: paciente.historial.insert
      parameters:
        - name: id
          in: path
          type: string
          description: id del paciente
          required: true
        - name: datos
          in: body
          required: true
          schema:
              $ref: '#/definitions/Historial'
      responses:
        '201':
          description: devuelve las cuentas
    get:
      tags:
        - Pacientes
      summary: Obtiene el historial del paciente
      x-swagger-router-controller: paciente.historial.find
      parameters:
        - name: id
          in: path
          type: string
          description: id del paciente
          required: true
      responses:
        '200':
          description: devuelve el historial del paciente
  /pacientes/{id}/historial/{historialId}:
    delete:
      tags:
        - Pacientes
      summary: Elimina registro del historial del paciente
      x-swagger-router-controller: paciente.historial.remove
      parameters:
        - name: id
          in: path
          type: string
          description: id del paciente
          required: true
        - name: historialId
          in: path
          type: string
          required: true
          description: id del registro del historial
      responses:
        '201':
          description: devuelve ok
    patch:
      tags:
        - Pacientes
      summary: Actualiza datos del historial del paciente
      x-swagger-router-controller: paciente.historial.update
      parameters:
        - name: id
          in: path
          type: string
          description: id del paciente
          required: true
        - name: historialId
          in: path
          type: string
          required: true
          description: id del registro del historial
        - name: notaClinica
          in: body
          required: true
          schema:
              $ref: '#/definitions/Historial'
      responses:
        '201':
          description: devuelve las cuentas
definitions:
  Paciente:
    type: object
    properties:
      dni:
        type: number
      nombre:
        type: string
      apellido:
        type: string
      edad:
        type: number
      fecNacimiento:
        type: string
        pattern: '^\d{2}/\d{2}/\d{4}$'
      primeraVisita:
        type: string
        pattern: '^\d{2}/\d{2}/\d{4}$'
      domicilio:
        type: string
      barrio:
        type: string
      telefono:
        type: string
      celular:
        type: string
      ocupacion:
        type: string
      alergia:
        type: string
      presion:
        type: string
      estatura:
        type: number
      peso:
        type: number
      tipoCalzado:
        type: number
      calzadoNro:
        type: number
      tacon:
        type: string
      varisa:
        type: string
      valguisa:
        type: string
      pedigrafia:
        type: string
      podoscopio:
        type: string
      normal:
        type: boolean
      plano:
        type: boolean
      cavo:
        type: boolean
      varo:
        type: boolean
      pronador:
        type: boolean
      supinador:
        type: boolean
      cuadrado:
        type: boolean
      griego:
        type: boolean
      egipcio:
        type: boolean
      lesionesPiel:
        type: string
      garra:
        type: boolean
      martillo:
        type: boolean
      maza:
        type: boolean
      halluxValgus:
        type: boolean
  Historial:
    type: object
    properties:
      descripcion:
        type: string
      observacion:
        type: string
