swagger: '2.0'
info:
  title: YourApp
  description: 'your App'
  version: 1.0.0
host: 'localhost:5000'
basePath: /service/
consumes:
  - application/json
produces:
  - application/json

paths:
  /pacientes:
    get:
      tags:
        - Pacientes
      summary: obtiene todos los pacientes
      x-swagger-router-controller: paciente.find
      parameters:
        - name: nombre
          in: query
          description: Nombre del paciente
          required: false
          type: string
        - name: apellido
          in: query
          required: false
          description: Apellido del paciente
          type: string
        - name: dni
          in: query
          description: dni del paciente
          required: false
          type: number
      responses:
        '200':
          description: Devuelve lista de pacientes
    post:
      tags:
        - Pacientes
      summary: Inserta datos del paciente
      x-swagger-router-controller: paciente.insert
      parameters:
        - name: datos
          in: body
          required: true
          schema:
              $ref: '#/definitions/paciente'
      responses:
        '201':
          description: devuelve las cuentas
  /pacientes/{id}:
    get:
      tags:
        - Pacientes
      summary: Obtiene el paciente por su id
      x-swagger-router-controller: paciente.find
      parameters:
        - name: id
          in: path
          type: string
          description: id del paciente
          required: true
      responses:
        '200':
          description:
            Devuelve paciente

  /server/time:
    get:
      tags:
        - hours
      summary: the local server time
      x-swagger-router-controller: server.time
      responses:
        '200':
          description: the local server time answer

  /about:
    get:
      tags:
        - about
      summary: About this API
      x-swagger-router-controller: about.about
      parameters:
        - name: name
          in: query
          required: false
          type: string
      responses:
        '200':
          description: About
          schema:
            $ref: '#/definitions/about'


definitions:
  about:
    type: object
    properties:
      version:
        type: string
      name:
        type: string
  paciente:
    type: object
    properties:
      dni:
        type: number
      nombre:
        type: string
      apellido:
        type: string
      domicilio:
        type: string
      telefono:
        type: number
      mail:
        type: string
