swagger: '2.0'
info:
  title: YourApp
  description: 'your App'
  version: 1.0.0
host: 'localhost:5000'
basePath: /service/
consumes:
  - application/json
  - multipart/form-data
produces:
  - application/json

paths:
  /pacientes:
    get:
      tags:
        - Pacientes
      summary: obtiene todos los pacientes
      x-swagger-router-controller: paciente.find
      parameters:
        - name: nombre
          in: query
          description: Nombre del paciente
          required: false
          type: string
        - name: apellido
          in: query
          required: false
          description: Apellido del paciente
          type: string
        - name: dni
          in: query
          description: dni del paciente
          required: false
          type: number
      responses:
        '200':
          description: Devuelve lista de pacientes
    post:
      tags:
        - Pacientes
      summary: Inserta datos del paciente
      x-swagger-router-controller: paciente.insert
      parameters:
        - name: dni
          in: formData
          required: true
          type: number
        - name: nombre
          in: formData
          type: string
          required: true
        - name: apellido
          in: formData
          type: string
          required: true
        - name: domicilio
          in: formData
          type: string
          required: true
        - name: telefono
          in: formData
          type: number
          required: false
        - name: fotoPerfil
          in: formData
          type: file
          required: false
      responses:
        '201':
          description: devuelve las cuentas
  /pacientes/{id}:
    get:
      tags:
        - Pacientes
      summary: Obtiene el paciente por su id
      x-swagger-router-controller: paciente.find
      parameters:
        - name: id
          in: path
          type: string
          description: id del paciente
          required: true
      responses:
        '200':
          description:
            Devuelve paciente
  /pacientes/{id}/historial:
    post:
      tags:
        - Pacientes
      summary: Inserta datos del historial del paciente
      x-swagger-router-controller: paciente.historial.insert
      parameters:
        - name: id
          in: path
          type: string
          description: id del paciente
          required: true
        - name: datos
          in: body
          required: true
          schema:
              $ref: '#/definitions/Historial'
      responses:
        '201':
          description: devuelve las cuentas

definitions:
  about:
    type: object
    properties:
      version:
        type: string
      name:
        type: string
  Paciente:
    type: object
    properties:
      dni:
        type: number
      nombre:
        type: string
      apellido:
        type: string
      domicilio:
        type: string
      telefono:
        type: number
      mail:
        type: string
  Historial:
    type: object
    properties:
      descripcion:
        type: string
      observacion:
        type: string
