swagger: '2.0'
info:
  title: YourApp
  description: 'your App'
  version: 1.0.0
host: 'localhost:5000'
basePath: /service/
consumes:
  - application/json
produces:
  - application/json

paths:
  /paciente:
    put:
      tags:
        - paciente
      summary: Inserta datos del paciente
      x-swagger-router-controller: paciente.insert
      parameters:
        - name: datos
          in: body
          required: true
          schema:
              $ref: '#/definitions/paciente'
      responses:
        '200':
          description: devuelve las cuentas

  /paciente/{id}:
    patch:
      tags:
         - paciente
      summary: Realiza un Update
      x-swagger-router-controller: paciente.update
      parameters:
        - name: datos
          in: path
          required: true

      responses:
        '200':
          description: Paciente

definitions:
  about:
    type: object
    properties:
      version:
        type: string
      name:
        type: string
  paciente:
    type: object
    properties:
      dni:
        type: number
      nombre:
        type: string
      apellido:
        type: string
      domicilio:
        type: string
      telefono:
        type: number
      mail:
        type: string
